### ISSUE TITLE
Trying local model with langchain throws error

### ISSUE THREAD

**Issue by qayyumabro** [whitead/paper-qa#182]
```
import paperscraper
from paperqa import Docs
from langchain.llms import LlamaCpp
from langchain import PromptTemplate, LLMChain
from langchain.callbacks.manager import CallbackManager
from langchain.embeddings import LlamaCppEmbeddings
from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler

llm = LlamaCpp(
    model_path="./ggml-gpt4all-j-v1.3-groovy.bin", callbacks=[StreamingStdOutCallbackHandler()]
)
embeddings = LlamaCppEmbeddings(model_path="./ggml-model-q4_0.bin")

docs = Docs(llm=llm, embeddings=embeddings)

keyword_search = 'bispecific antibody manufacture'
papers = paperscraper.search_papers(keyword_search, limit=2)
for path,data in papers.items():
    try:
        docs.add(path,chunk_chars=500)
    except ValueError as e:
        print('Could not read', path, e)

answer = docs.query("What manufacturing challenges are unique to bispecific antibodies?")
print(answer)
```

Throws this error:
```
WARNING:paperscraper.load_dumps: No dump found for biorxiv. Skipping entry.
WARNING:paperscraper.load_dumps: No dump found for chemrxiv. Skipping entry.
WARNING:paperscraper.load_dumps: No dump found for medrxiv. Skipping entry.
WARNING:paperscraper.load_dumps: No dumps found for either biorxiv or medrxiv. Consider using paperscraper.get_dumps.* to fetch the dumps.
Traceback (most recent call last):
  File "C:\Users\Muhammad Qayyum\Desktop\gpt4all\new\paper.py", line 2, in <module>
    from paperqa import Docs
  File "C:\Python311\Lib\site-packages\paperqa\__init__.py", line 1, in <module>
    from .docs import Answer, Docs, PromptCollection, Doc, Text
  File "C:\Python311\Lib\site-packages\paperqa\docs.py", line 35, in <module>
    class Docs(BaseModel, arbitrary_types_allowed=True, smart_union=True):
  File "C:\Python311\Lib\site-packages\paperqa\docs.py", line 43, in Docs
    llm: Union[str, BaseLanguageModel] = ChatOpenAI(
                                         ^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\langchain\load\serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ChatOpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)
```

**Comment by whitead** [comment]
Yes, you must just set that variable to something generic. Like:

```sh
export OPENAI_API_KEY=foo
```

It is a problem with langchain.

**Comment by qayyumabro** [comment]
Thanks
