### ISSUE TITLE
Add texts not working

### ISSUE THREAD

**Issue by phamkhactu** [whitead/paper-qa#188]
Hi,

Thanks for great repo!!
I've seen your Readme to add document for search
```
from paperqa import Docs

model_id = "llama-2-7b-chat/7B/ggml-model-int8.bin"
llm = LlamaCpp(
    model_path=model_id, callbacks=[StreamingStdOutCallbackHandler()]
)

embeddings = LlamaCppEmbeddings(model_path=model_id)
docs = Docs(llm=llm, embeddings=embeddings)

with open("2503.json", "r") as r:
    data = json.load(r)

texts = []
for d in data:
    texts.append(d["output"])


docs.add_texts(texts=texts, doc=None)
answer = docs.query("What manufacturing challenges are unique to bispecific antibodies?")
print(answer.formatted_answer)

```
texts format:["text1, "text2", "text3", "text4"]
I get error.
```
Traceback (most recent call last):
  File "question_answering.py", line 33, in <module>
    docs.add_texts(texts=texts, doc="test")
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/site-packages/paperqa/docs.py", line 238, in add_texts
    if doc.dockey in self.docs:
AttributeError: 'str' object has no attribute 'dockey'
Exception ignored in: <function Llama.__del__ at 0x7f86d2a30c10>
Traceback (most recent call last):
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/site-packages/llama_cpp/llama.py", line 1508, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function Llama.__del__ at 0x7f86d2a30c10>
Traceback (most recent call last):
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/site-packages/llama_cpp/llama.py", line 1508, in __del__
TypeError: 'NoneType' object is not callable
```
Maybe it comes from doc object in function ```add_texts```

I am very happy if you can produce some code example  to loads from texts chunk as my case.

Thank you!

**Comment by whitead** [comment]
it appears you had the doc set to be `"test"`, whereas `doc` should be of type `Doc` (see definition here https://github.com/whitead/paper-qa/blob/main/paperqa/types.py#L31)
