### ISSUE TITLE
[Error]: Running example.

### ISSUE THREAD

**Issue by phamkhactu** [whitead/paper-qa#189]
I've followed [your example](https://github.com/whitead/paper-qa/blob/main/tests/test_paperqa.py#L737) except for adding embedding model
```
docs = Docs(llm=llm, embeddings=embeddings)

```
Here is my code:
```
model_id = "llama-2-7b-chat/7B/ggml-model-int8.bin"
llm = LlamaCpp(
    model_path=model_id, callbacks=[StreamingStdOutCallbackHandler()],
    max_tokens=512,
    truncate=True,
    # n_ctx=512,
)

embeddings = LlamaCppEmbeddings(model_path=model_id)
docs = Docs(llm=llm, embeddings=embeddings)

# # keyword_search = 'bispecific antibody manufacture'
# # papers = paperscraper.search_papers(keyword_search, limit=2)

docs.add_url(
    "https://en.wikipedia.org/wiki/National_Flag_of_Canada_Day",
    citation="WikiMedia Foundation, 2023, Accessed now",
    dockey="test",
    # chunk_chars=512
)

answer = docs.query("What country was Bates Born in?")
print(answer)
```
I get error not callable:
```
File "question_answering.py", line 52, in <module>
    docs.add_url(
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/site-packages/paperqa/docs.py", line 160, in add_url
    return self.add_file(
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/site-packages/paperqa/docs.py", line 138, in add_file
    return self.add(
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/site-packages/paperqa/docs.py", line 225, in add
    if self.add_texts(texts, doc):
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/site-packages/paperqa/docs.py", line 248, in add_texts
    text_embeddings = self.embeddings.embed_documents([t.text for t in texts])
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/site-packages/langchain/embeddings/llamacpp.py", line 110, in embed_documents
    embeddings = [self.client.embed(text) for text in texts]
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/site-packages/langchain/embeddings/llamacpp.py", line 110, in <listcomp>
    embeddings = [self.client.embed(text) for text in texts]
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/site-packages/llama_cpp/llama.py", line 812, in embed
    return list(map(float, self.create_embedding(input)["data"][0]["embedding"]))
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/site-packages/llama_cpp/llama.py", line 776, in create_embedding
    self.eval(tokens)
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/site-packages/llama_cpp/llama.py", line 478, in eval
    self.scores[self.n_tokens + offset : self.n_tokens + n_tokens, :].reshape(
ValueError: could not broadcast input array from shape (32000,) into shape (0,)
Exception ignored in: <function Llama.__del__ at 0x7fb7780c2c10>
Traceback (most recent call last):
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/site-packages/llama_cpp/llama.py", line 1508, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function Llama.__del__ at 0x7fb7780c2c10>
Traceback (most recent call last):
  File "/home/tupk/anaconda3/envs/nlp/lib/python3.8/site-packages/llama_cpp/llama.py", line 1508, in __del__
TypeError: 'NoneType' object is not callable
```

**Comment by whitead** [comment]
It appears to be a problem with the llama embeddings - can you try just embedding a string with that alone?

**Comment by phamkhactu** [comment]
> er = docs.query("What country was Bates Born in?")
> print(answer)

@whitead Yes, It comes from embedding.
