### ISSUE TITLE
Demo on Huggingface is down

### ISSUE THREAD

**Issue by brandco** [whitead/paper-qa#196]
I just encountered this error on the Hugging Face demo (https://huggingface.co/spaces/whitead/paper-qa)

**Runtime error**
Space failed. Exit code: 1. Reason: Traceback (most recent call last):
  File "app.py", line 2, in <module>
    import paperqa
  File "/home/user/.local/lib/python3.8/site-packages/paperqa/__init__.py", line 1, in <module>
    from .docs import Answer, Docs, PromptCollection, Doc, Text
  File "/home/user/.local/lib/python3.8/site-packages/paperqa/docs.py", line 35, in <module>
    class Docs(BaseModel, arbitrary_types_allowed=True, smart_union=True):
  File "/home/user/.local/lib/python3.8/site-packages/paperqa/docs.py", line 43, in Docs
    llm: Union[str, BaseLanguageModel] = ChatOpenAI(
  File "/home/user/.local/lib/python3.8/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ChatOpenAI
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)

**Tail of the container logs:**
  File "app.py", line 119, in download_repo
    raise ValueError('Unknown Github Repo')
ValueError: Unknown Github Repo
Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')).

**Comment by evanVerinomics** [comment]
I'm having the same issue, any solutions?
