### ISSUE TITLE
Issue importing local GPT4ALL Falcon model on Windows?

### ISSUE THREAD

**Issue by windowshopr** [whitead/paper-qa#202]
Python 3.8, Windows 10, paper-qa==3.11.2

```
from langchain.embeddings import GPT4AllEmbeddings
from langchain.llms import GPT4All
from dotenv import load_dotenv
import os
# Import the OPEN_AI_API_KEY from the .env file BEFORE IMPORTING paperqa!
# https://github.com/whitead/paper-qa/issues/149
load_dotenv()
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
os.environ['OPENAI_API_KEY'] = OPENAI_API_KEY
# Put this AFTER importing the OPEN_AI_API_KEY
from paperqa import Docs

# Global variables
MODELS_FOLDER = "C:\\Users\\chalu\\AppData\\Local\\nomic.ai\\GPT4All\\"
LLM_MODEL_NAME = "ggml-model-gpt4all-falcon-q4_0.bin"
model_path = MODELS_FOLDER + LLM_MODEL_NAME
print("Model Path:",model_path)
LLM = GPT4All(model_path=model_path)
```

```
Model Path: C:\Users\chalu\AppData\Local\nomic.ai\GPT4All\ggml-model-gpt4all-falcon-q4_0.bin

Traceback (most recent call last):
  File ".\main.py", line 21, in <module>
    LLM = GPT4All(model_path=model_path)
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python38\lib\site-packages\langchain\load\serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic\main.py", line 1102, in pydantic.main.validate_model
  File "C:\Users\chalu\AppData\Local\Programs\Python\Python38\lib\site-packages\langchain\llms\gpt4all.py", line 137, in validate_environment     
    full_path = values["model"]
KeyError: 'model'
```

**Comment by whitead** [comment]
It looks like this is an error on the line for instantiating GPT4ALL, not anything to do with paper-qa. I'm not sure GPT4ALL works
