### ISSUE TITLE
ZoteroDB import issue

### ISSUE THREAD

**Issue by mdroidian** [whitead/paper-qa#57]
I'm trying to run https://github.com/whitead/paper-qa/blob/b20f4e9c72783735bf23cc1c43984c179dd5c731/README.md?plain=1#L172-L180

I've installed 
```
pip install paper-qa
pip install pyzotero
```
I added a `.env` and tested it.

I get this error:
```
Traceback (most recent call last):
  File "C:\Users\mclic\AppData\Local\Programs\Python\Python39\lib\site-packages\paperqa\contrib\zotero.py", line 9, in <module>
    from pyzotero import zotero
  File "C:\Users\mclic\Desktop\Projects\dev\paper-qa\pyzotero.py", line 4, in <module>
    from paperqa.contrib import ZoteroDB
ImportError: cannot import name 'ZoteroDB' from partially initialized module 'paperqa.contrib' (most likely due to a circular import) (C:\Users\mclic\AppData\Local\Programs\Python\Python39\lib\site-packages\paperqa\contrib\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mclic\Desktop\Projects\dev\paper-qa\pyzotero.py", line 4, in <module>
    from paperqa.contrib import ZoteroDB
  File "C:\Users\mclic\AppData\Local\Programs\Python\Python39\lib\site-packages\paperqa\contrib\__init__.py", line 1, in <module>
    from .zotero import ZoteroDB
  File "C:\Users\mclic\AppData\Local\Programs\Python\Python39\lib\site-packages\paperqa\contrib\zotero.py", line 11, in <module>
    raise ImportError("Please install pyzotero: `pip install pyzotero`")
ImportError: Please install pyzotero: `pip install pyzotero`
```

Any ideas what I should try next? 😀

**Comment by mdroidian** [comment]
I've also tried
```
import dotenv
dotenv.load_dotenv()

from paperqa import Docs
from paperqa.contrib import ZoteroDB

docs = Docs()
zotero = ZoteroDB(library_type="user")  # "group" if group library

for item in zotero.iterate(limit=20):
    if item.num_pages > 30:
        continue  # skip long papers
    docs.add(item.pdf, key=item.key)
```

Same error.

**Comment by whitead** [comment]
Hi @mdroidian can you tell me what version of `paper-qa` you're on?

**Comment by whitead** [comment]
@mdroidian can you upgrade and try again?

**Comment by MilesCranmer** [comment]
Hey @mdroidian,
I can't reproduce the issue, this code works fine for me. Perhaps you installed pyzotero into a different env?

For the record, I'm using the following `pyproject.toml` (with [`poetry`](https://python-poetry.org/)):

```toml
[tool.poetry]
name = "paperqa"
version = "0.1.1"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "paperqa"}]

[tool.poetry.dependencies]
python = ">=3.8.1,<3.12"
pytest = "^7.2.2"
pre-commit = "^3.2.2"
requests = "^2.28.2"
ipython = "^8.12.0"
jupyter = "^1.0.0"
ipykernel = "^6.22.0"
langchain = ">=0.0.98"
html2text = "^2020.1.16"
openai = ">=0.27.0"
pypdf = "^3.7.0"
faiss-cpu = "^1.7.3"
pycryptodome = "^3.17"
tiktoken = "^0.3.3"
pyzotero = "^1.5.5"
llama-cpp-python = "^0.1.32"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```


Cheers,
Miles

**Comment by jonathanmc** [comment]
Ahaha separately I had the same problem and just happened to peruse this thread. So, thanks for the assist!
